WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;

namespace WebUI.Controllers
{
  [Authorize]
    public class AdminController : Controller
    {
        IBookRepository repository;

        public AdminController(IBookRepository repo)
        {
            repository = repo;
        }
        public ViewResult Index()
        {
            return View(repository.Books);
        }

        public ViewResult Edit(int id)
        {
            Book book = repository.Books.FirstOrDefault(b => b.Id == id);
            return View(book);
        }

        [HttpPost]
        public ActionResult Edit(Book book,HttpPostedFileBase file=null)
        {
            if (ModelState.IsValid)
            {
                repository.SaveBook(book, file);
                TempData["message"] = string.Format("Изменения информации о книге \"{0}\" сохранены", book.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            }
        }

        public ViewResult Create()
        {
            return View(new Book());
        }


        [HttpPost]
        public ActionResult Create(Book book, HttpPostedFileBase file = null)
        {
            if (ModelState.IsValid)
            {
                repository.SaveBook(book,file);
                TempData["message"] = string.Format("Книга \"{0}\" успешно добавлена!", book.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            } 
        }

        public ActionResult Delete(int id = 0)
        {
            repository.DeleteBook(id);
            return RedirectToAction("Index");
        }
    }
}

WebUI/Views/Admin/Create.cshtml
@model Domain.Entities.Book
@{
    ViewBag.Title = "Панель администратора - Добавление товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    /* ОТключение проверки достоверности данных на стороне клиента (только на этой вьюхе)
     * HtmlHelper.ClientValidationEnabled = false;
     HtmlHelper.UnobtrusiveJavaScriptEnabled = false;*/
}
<div class="panel">
    <div class="panel-heading">
        <h2>Добавление новой книги</h2>
    </div>


    @using (Html.BeginForm())
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.Id)
            @foreach (var prop in ViewData.ModelMetadata.Properties)
            {
                if (prop.PropertyName != "Id" || prop.PropertyName != "ImagePath")
                {
                    <div class="form-group">
                        <label>@(prop.DataTypeName ?? prop.PropertyName)</label>
                        @if (prop.PropertyName == "Description")
                        {
                            @Html.TextArea(prop.PropertyName, null, new {@class = "form-control", rows = 5})
                        }
                        else
                        {
                            @Html.TextBox(prop.PropertyName, null, new {@class = "form-control"})
                        }
                        @Html.ValidationMessage(prop.PropertyName)
                    </div>
                }
            }
            <div class="editor-label">
                @Html.Label("Обложка")
            </div>
            <div class="editor-field">
                @Html.TextBox("file", "", new {@class = "btn btn-default", type = "file"})
            </div>

        </div>
        

        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
        </div>
    }

</div>

WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Book

@{
    ViewBag.Title = "Панель администратора - редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
   /* ОТключение проверки достоверности данных на стороне клиента (только на этой вьюхе)
    * HtmlHelper.ClientValidationEnabled = false;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;*/
}
<div class="panel">
    <div class="panel-heading">
        <h2>Редактирование книги "@Model.Name"</h2>
    </div>


   @using (Html.BeginForm("Edit", "Admin", FormMethod.Post,
                new { enctype = "multipart/form-data" }))
   {

        <div class="panel-body">
            @Html.HiddenFor(m=>m.Id)
            @foreach (var prop in ViewData.ModelMetadata.Properties)
            {
                if (prop.PropertyName != "Id"&& prop.PropertyName!="ImagePath")
                {
                    <div class="form-group">
                        <label>@(prop.DisplayName ?? prop.PropertyName)</label>

                        @if (prop.PropertyName == "Description")
                        {
                            @Html.TextArea(prop.PropertyName,null,new{@class="form-control",rows=5})
                        }
                        else
                        {
                            @Html.TextBox(prop.PropertyName,null,new{@class = "form-control"})
                        }
                        @Html.ValidationMessage(prop.PropertyName)
                    </div>
                }
            }

            <div class="editor-label">
                @Html.Label("Обложка")
            </div>
            <div class="editor-field">
                @Html.TextBox("file", "", new { @class = "btn btn-default", type = "file" })
            </div>
        </div>

    <div class="panel-footer">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
        @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
    </div>
    }

</div>

WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Book>

@{
    ViewBag.Title = "Список товаров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="center-block">
    <h2>Панель Администратора</h2>
    <h3>Список книг</h3>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th >
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>@Html.DisplayName("С обложкой")</th>
                <th>
                    @Html.DisplayNameFor(model => model.Author)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th class="text-center">действия</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @item.Id
                    </td>
                    <td>
                        @Html.ActionLink(item.Name, "Edit", new {item.Id})
                    </td>
                    <td>
                        @Html.CheckBox("обложка", new { @checked = String.IsNullOrEmpty(item.ImagePath) ? "unchecked" : "checked", @disabled = "disabled" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author)
                    </td>

                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("Id", item.Id)
                            <input type="submit" class="btn btn-default btn-xs" value="Удалить" />
                        }
                    </td>
                </tr>
            }

        </table>
    </div>

    <div class="panel-footer">
        @Html.ActionLink("Добавить", "Create", null, new {@class = "btn btn-default"})
    </div>
</div>