WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
       private IBookRepository repository;
        private IOrderProcessor orderProcessor;


        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public CartController(IBookRepository repo,IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public RedirectToRouteResult AddToCart(Cart cart, int Id, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.Id == Id);

            if (book != null)
            {
               cart.AddItem(book,1);
            }
            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int Id, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.Id == Id);

            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("","Извините, корзина пуста!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.processOrder(cart,shippingDetails);
                cart.Clear();
                return View("Complete");
            }

                return View(new ShippingDetails());
            
        }
        
    }
}

WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string genre = null)
        {
            ViewBag.SelectedGenre = genre;
            IEnumerable<string> genres = repository.Books
                .Select(book => book.Genre)
                .Distinct()
                .OrderBy(x => x);

           


            return PartialView("FlexMenu", genres);
        }
    }
}

WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet"/>
    <link href="~/Content/Site.css" rel="stylesheet"/>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
<div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>
</body>
</html>

WebUI/Views/Shared/_BookSummary.cshtml
@model Domain.Entities.Book

<div class="well">
    <div class="row">

        <div class="col-xs-3">
            @if (Model.ImagePath != null)
            {
                <img src="@Url.Content("~/Images/" + System.IO.Path.GetFileName(Model.ImagePath))" alt="" class="img-thumbnail" />
            }
            else
            {
                <img src="@Url.Content("~/Images/Book-NoName.jpg")" alt="" class="img-thumbnail" style="width:250px" />
            } 
        </div>
        
       
        <div class="col-xs-7">

            <h3>
                <strong>@Model.Name</strong>
            </h3>
            <h4>
                <strong>@Model.Author</strong>
            </h4>

            <h5>
                <p >
                    @Model.Description
                </p>
            </h5>
        </div>
        <div class="col-xs-2" align="right">
            
            <div class="input-group">
                <h2>
                    <strong class="label label-primary">@Model.Price.ToString("# руб.")</strong>
                </h2>

                <h2>
                    @using (Html.BeginForm("AddToCart", "Cart"))
                    {
                        @Html.HiddenFor(x => x.Id)
                        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                        <input type="submit" class="btn btn-success" id="basic-url" value="В корзину" />
                    }
                </h2>
            </div>



        </div>
       
    </div>
 
</div>

WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.js"></script>
    

</head>
<body>
<div data-role="page" id="page1">
    <div data-theme="a" data-role="header" data-position="fixed">
        <h3>BookStore</h3>
        @Html.Action("Menu", "Nav")
    </div>

    <div data-role="content">
        <ul data-role="listview" data-dividertheme="b" data-inset="false">
            <li>@RenderBody()</li>
        </ul>
    </div>
</div>



</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet"/>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>

</head>
<body>

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">
        <span class="hidden-xs">  BookStore - Книжный магазин</span>
        <div class="visible-xs">Book</div>
        <div class="visible-xs">Store</div>
    </a>
    @Html.Action("Summary", "Cart")
</div>

<div class="visible-xs">
    @Html.Action("Menu", "Nav", new { horizontalNav = true })
</div>

    <div class="row panel">
        <div id="genres" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>

        <div class="col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>